// Generated by CoffeeScript 1.8.0
(function() {
  var http, server;

  http = require('http');

  server = http.createServer(function(req, res) {
    res.writeHeader(200, {
      "Content-Type": "text/html"
    });
    res.write('<p>Headers:</p>');
    res.write(JSON.stringify(req.headers));
    res.write('<hr/><p><i>Powered by nodejs</i></p>');
    return res.end();
  });

  server.listen(8080);

  console.log('httpd start @8080');

}).call(this);
