// Generated by CoffeeScript 1.8.0
(function() {
  var http, server;

  http = require('http');

  server = http.createServer(function(req, res) {
    res.writeHeader(200, {
      "Content-Type": "text/plain"
    });
    res.write('From nodejs');
    return res.end;
  });

  server.listen(8080);

  console.log('httpd start @8080');

}).call(this);
