// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var jsdom;

  jsdom = require('jsdom');

  process.on('uncaughtException', function(err) {
    return console.log(err);
  });

  process.on('message', function(m) {
    var html, id;
    id = m[0];
    html = m[1];
    return jsdom.env(html, function(errors, window) {
      var $, body, title;
      $ = require('jquery')(window);
      title = $('#content_body > center:nth-child(1) > span').text();
      body = $('#content_body').text();
      console.log('Parsed ProblemID: ' + id + ', Title: ' + title);
      process.send([id, title, body]);
      return window.close();
    });
  });

}).call(this);
